# Generated by Django 6.1.1 on 2026-10-07 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_temporaryroute_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='end_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='route',
            name='start_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='temporaryroute',
            name='end_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='temporaryroute',
            name='start_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
