package com.example.runtime.ui.route

import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.example.runtime.R
import com.example.runtime.data.remote.GeneratedRouteData
import com.example.runtime.data.remote.GeoJsonPoint
import com.example.runtime.data.repository.RouteRepository
import com.example.runtime.ui.common.UiText
import com.example.runtime.ui.common.toUiText
import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.launch
import kotlin.math.roundToInt

class RouteViewModel(
    private val repository: RouteRepository = RouteRepository(),
) : ViewModel() {

    var startPointInput by mutableStateOf("")
    var distanceInput by mutableStateOf("")

    var error by mutableStateOf<UiText?>(null)
        private set

    var generated by mutableStateOf<GeneratedRouteData?>(null)
        private set

    var saveState by mutableStateOf<SaveState>(SaveState.Idle)
        private set

    private var pendingDistanceMeters: Int? = null
    private var pendingLanguage: String = DEFAULT_LANGUAGE
    private var isGenerating = false

    fun prepare(language: String): Boolean {
        val meters = distanceInput.trim().toDoubleOrNull()
            ?.takeIf { it.isFinite() }
            ?.let { (it * 1000).roundToInt() }
        if (meters == null || meters <= MIN_DISTANCE_METERS) {
            error = UiText.Resource(R.string.error_distance_min)
            return false
        }
        error = null
        pendingDistanceMeters = meters
        pendingLanguage = if (language in SUPPORTED_LANGUAGES) language else DEFAULT_LANGUAGE
        return true
    }

    fun generate(onSuccess: () -> Unit, onFailure: () -> Unit) {
        val distanceMeters = pendingDistanceMeters ?: return onFailure()
        if (isGenerating) return
        isGenerating = true
        viewModelScope.launch {
            try {
                generated = repository.generate(SNU, distanceMeters, pendingLanguage)
                saveState = SaveState.Idle
                onSuccess()
            } catch (e: CancellationException) {
                throw e
            } catch (e: Exception) {
                error = e.toUiText()
                onFailure()
            } finally {
                isGenerating = false
            }
        }
    }

    fun save() {
        val route = generated ?: return
        if (saveState == SaveState.Saving || saveState == SaveState.Saved) return
        saveState = SaveState.Saving
        viewModelScope.launch {
            saveState = try {
                repository.saveTemporaryRoute(route.temporaryRouteId)
                SaveState.Saved
            } catch (e: CancellationException) {
                throw e
            } catch (e: Exception) {
                SaveState.Failed(e.toUiText())
            }
        }
    }

    companion object {
        private const val MIN_DISTANCE_METERS = 100
        private const val DEFAULT_LANGUAGE = "en"
        private val SUPPORTED_LANGUAGES = setOf("en", "ko")
        private val SNU = GeoJsonPoint.of(longitude = 126.9520, latitude = 37.4600)
    }
}

sealed interface SaveState {
    data object Idle : SaveState
    data object Saving : SaveState
    data object Saved : SaveState
    data class Failed(val message: UiText) : SaveState
}
