package com.example.runtime.ui.route

import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.example.runtime.data.remote.ApiClient
import com.example.runtime.data.remote.GenerateRouteRequest
import com.example.runtime.data.remote.GeneratedRouteData
import com.example.runtime.data.remote.GeoJsonPoint
import com.example.runtime.data.remote.toUserMessage
import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.launch
import kotlin.math.roundToInt

class RouteViewModel : ViewModel() {

    var startPointInput by mutableStateOf("")
    var distanceInput by mutableStateOf("")

    var error by mutableStateOf<String?>(null)
        private set

    var generated by mutableStateOf<GeneratedRouteData?>(null)
        private set

    private var pendingRequest: GenerateRouteRequest? = null
    private var isGenerating = false

    fun prepare(): Boolean {
        val meters = distanceInput.trim().toDoubleOrNull()
            ?.takeIf { it.isFinite() }
            ?.let { (it * 1000).roundToInt() }
        if (meters == null || meters <= MIN_DISTANCE_METERS) {
            error = "Enter a distance greater than 0.1 km."
            return false
        }
        error = null
        pendingRequest = GenerateRouteRequest(startingPoint = SNU, distance = meters)
        return true
    }

    fun generate(onSuccess: () -> Unit, onFailure: () -> Unit) {
        val request = pendingRequest ?: return onFailure()
        if (isGenerating) return
        isGenerating = true
        viewModelScope.launch {
            try {
                generated = ApiClient.api.generateRoute(request).data
                    ?: throw IllegalStateException("Empty response from server.")
                onSuccess()
            } catch (e: CancellationException) {
                throw e
            } catch (e: Exception) {
                error = e.toUserMessage()
                onFailure()
            } finally {
                isGenerating = false
            }
        }
    }

    companion object {
        private const val MIN_DISTANCE_METERS = 100
        private val SNU = GeoJsonPoint.of(longitude = 126.9520, latitude = 37.4600)
    }
}
